//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BioBotApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class SerialComunication : global::System.Configuration.ApplicationSettingsBase {
        
        private static SerialComunication defaultInstance = ((SerialComunication)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SerialComunication())));
        
        public static SerialComunication Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("19500")]
        public int gCodeSerialBaudRate {
            get {
                return ((int)(this["gCodeSerialBaudRate"]));
            }
            set {
                this["gCodeSerialBaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int gCodeSerialDataBits {
            get {
                return ((int)(this["gCodeSerialDataBits"]));
            }
            set {
                this["gCodeSerialDataBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string gCodeSerialPortName {
            get {
                return ((string)(this["gCodeSerialPortName"]));
            }
            set {
                this["gCodeSerialPortName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.IO.Ports.Parity gCodeSerialParity {
            get {
                return ((global::System.IO.Ports.Parity)(this["gCodeSerialParity"]));
            }
            set {
                this["gCodeSerialParity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("One")]
        public global::System.IO.Ports.StopBits gCodeSerialStopBits {
            get {
                return ((global::System.IO.Ports.StopBits)(this["gCodeSerialStopBits"]));
            }
            set {
                this["gCodeSerialStopBits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.IO.Ports.Handshake gCodeSerialHandshake {
            get {
                return ((global::System.IO.Ports.Handshake)(this["gCodeSerialHandshake"]));
            }
            set {
                this["gCodeSerialHandshake"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gCodeSerialRtsEnable {
            get {
                return ((bool)(this["gCodeSerialRtsEnable"]));
            }
            set {
                this["gCodeSerialRtsEnable"] = value;
            }
        }
    }
}
